sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_24ce0443de73_key -iv $encrypted_24ce0443de73_iv
  -in travis-deploy-gae.json.enc -out travis-deploy-gae.json -d
- docker build -t touomiwilly/docker-react -f Dockerfile.dev .
script:
- docker run touomiwilly/docker-react npm run test -- --coverage
deploy:
  provider: gae
  project: crack-map-230602
  keyfile: travis-deploy-gae.json
  verbosity: debug
  on: master
