sudo: required
services:
  - docker

before_install:
  - docker build -t touomiwilly/docker-react -f Dockerfile.dev .

script:
  - docker run touomiwilly/docker-react npm run test -- --coverage

deploy:
  provider: "gae"
  keyfile: "account.json"
  project: "crack-map-230602"
  on: master
